import type { BlogPost } from './blogs';

// Expanded bodies for the three thin legacy posts (they were ~150-250 words = "thin content").
export const LEGACY_OVERRIDES: Record<string, Partial<BlogPost>> = {
  'high-protein-foods-for-muscle-building': {
    updated: '2026-09-28',
    tools: ['protein-calculator', 'macro-calculator'],
    readTime: '7 min read',
    body: [
      `Muscle isn't built in the gym – it's built at the dinner table. You can train perfectly and still stall if your plate does not supply enough protein. This guide lists the best high-protein foods, how much protein each gives you, and how to build them into a day of eating.`,
      `## How much protein do you actually need?`,
      `Research suggests muscle growth benefits level off around 1.6 g of protein per kg of bodyweight per day, with 2.2 g/kg as a sensible upper end. That is about 0.7–1 g per pound. A 70 kg person should aim for roughly 110–150 g per day. Use the [protein calculator](/tools/protein-calculator) for your exact figure.`,
      `## The best high-protein foods (approximate protein per serving)`,
      `- **Chicken breast, 150 g cooked:** about 45 g. Lean, cheap and easy to batch cook.`,
      `- **Eggs, 3 large:** about 18 g, plus choline and vitamin D from the yolk.`,
      `- **Fish (salmon, tuna, mackerel), 150 g:** 30–35 g, plus omega-3 fats.`,
      `- **Greek yogurt, 200 g:** about 18–20 g. Thick curd (hung dahi) is a similar option.`,
      `- **Paneer, 100 g:** about 18–20 g, a staple for vegetarians in India.`,
      `- **Lentils (dal), 1 cooked cup:** about 18 g, with plenty of fibre.`,
      `- **Chickpeas / rajma, 1 cooked cup:** 14–15 g.`,
      `- **Tofu, 150 g:** about 12–15 g; **soya chunks, 50 g dry:** about 26 g.`,
      `- **Whey protein, 1 scoop:** 20–25 g when whole food is inconvenient.`,
      `## A sample 120 g protein day`,
      `- **Breakfast:** 3 eggs plus 1 cup of curd – about 30 g.`,
      `- **Lunch:** dal, rice and 100 g paneer or chicken – about 35–40 g.`,
      `- **Snack:** roasted chana or Greek yogurt – about 15–20 g.`,
      `- **Dinner:** 150 g fish or tofu with vegetables and roti – about 35 g.`,
      `## Common protein mistakes`,
      `Most people eat almost all their protein at dinner. Spreading 20–40 g across 3–4 meals is better for muscle repair. The second mistake is relying on protein bars and shakes; whole foods bring fibre, vitamins and better fullness for fewer calories. Finally, do not forget total calories: protein builds muscle only if you also eat enough overall.`,
      `## Quick way to hit your number without a food scale`,
      `Aim for a palm-sized portion of protein at each meal. For most adults that lands close to 1.6–2.2 g/kg. Need a vegetarian focus? See [high-protein vegetarian Indian foods](/blogs/high-protein-vegetarian-indian-foods).`,
    ],
  },
  'beginner-workout-plan-at-home': {
    updated: '2026-09-28',
    tools: ['calories-burned-calculator', 'one-rep-max-calculator'],
    readTime: '8 min read',
    body: [
      `The best beginner plan is the one you actually finish. This is a three-day, no-equipment routine built for your first four to eight weeks, with clear progressions so you keep improving without a gym.`,
      `## How the plan is structured`,
      `Train three non-consecutive days a week (for example Monday, Wednesday, Friday). Each session takes 25–35 minutes. Do 3 sets of each exercise, resting 60–90 seconds between sets, and stop each set with 1–2 reps left in the tank.`,
      `## Day 1 – Lower body`,
      `- **Bodyweight squats:** 3 × 12–15. Sit back and keep your heels down.`,
      `- **Glute bridges:** 3 × 15. Squeeze at the top for one second.`,
      `- **Walking lunges:** 3 × 10 each leg.`,
      `- **Calf raises:** 3 × 15–20 on the edge of a step.`,
      `## Day 2 – Upper body`,
      `- **Push-ups (knees down if needed):** 3 × 6–12.`,
      `- **Doorframe or table rows:** 3 × 10–12.`,
      `- **Pike push-ups:** 3 × 6–10 for shoulders.`,
      `- **Plank:** 3 × 20–40 seconds.`,
      `## Day 3 – Full body`,
      `- **Squat to press with a backpack or water bottles:** 3 × 12.`,
      `- **Reverse lunges:** 3 × 10 each leg.`,
      `- **Bird-dogs:** 3 × 10 each side.`,
      `- **Side plank:** 3 × 20–30 seconds each side.`,
      `## How to progress every week`,
      `Add one rep per set each week. When you reach the top of the rep range on every set, move to a harder version: slower reps (3 seconds down), single-leg variations, or elevated feet push-ups. This is progressive overload, the reason training works.`,
      `## Why this works for beginners`,
      `Consistency beats intensity for the first month. The plan is short enough that skipping it feels harder than doing it. Pair it with daily walking and enough protein (see our [protein calculator](/tools/protein-calculator)), and use the [calories burned calculator](/tools/calories-burned-calculator) to see roughly what each session costs.`,
      `## When to move on`,
      `After 8–12 weeks, or when 3 sets of 15 feel easy, consider a barbell or dumbbell programme such as our [beginner strength training plan](/blogs/strength-training-for-beginners-uk-us-2026). Stop any exercise that causes sharp pain and see a professional if it persists.`,
    ],
  },
  'how-much-water-should-you-drink-daily': {
    updated: '2026-09-28',
    tools: ['water-intake-calculator'],
    readTime: '6 min read',
    body: [
      `"Drink 8 glasses a day" is easy to remember but it was never based on your bodyweight, climate or activity. Here is how to work out how much water you really need, and how to tell if you are drinking enough.`,
      `## What the health authorities say`,
      `US guidance (National Academies) suggests about 3.7 litres of total water a day for men and 2.7 litres for women. European guidance (EFSA) suggests about 2.5 L and 2.0 L. "Total water" includes all drinks and the roughly 20% that comes from food, so actual drinking water is lower.`,
      `## A practical formula`,
      `A widely used baseline is 30–35 ml per kg of bodyweight per day. A 60 kg person needs about 1.8–2.1 L; an 80 kg person about 2.4–2.8 L. Our [water intake calculator](/tools/water-intake-calculator) does this for you and adjusts for activity.`,
      `## When you need more`,
      `- **Hot or humid weather:** in Indian summers you can lose 1 L or more of sweat per hour of outdoor exercise.`,
      `- **Exercise:** add about 500–1,000 ml per hour of training.`,
      `- **Pregnancy and breastfeeding:** guidelines recommend roughly 300–700 ml extra.`,
      `- **Illness with fever, vomiting or diarrhoea:** replace fluids and electrolytes.`,
      `- **High altitude and high-protein or high-fibre diets** also raise needs.`,
      `## Signs you are dehydrated`,
      `Dark yellow urine, headaches, dry mouth, dizziness, unusual tiredness and reduced urination are all warning signs. Pale straw-coloured urine is the easiest daily check.`,
      `## Do tea, coffee and other drinks count?`,
      `Yes. Tea, coffee, milk, buttermilk and soups all count toward fluid intake. Caffeine has a mild diuretic effect but regular drinkers adapt, so the net effect is still hydrating. Sugary drinks add calories without benefit, so water should be the default.`,
      `## Can you drink too much?`,
      `In rare cases, drinking several litres in a short time can dilute blood sodium (hyponatraemia), mostly seen in endurance events. Sip steadily through the day instead of forcing large amounts at once.`,
      `## Easy habits`,
      `Drink a glass on waking, keep a bottle at your desk, and have one with every meal. If you struggle with plain water, add lemon, mint or cucumber. Athletes doing runs over an hour should also consider electrolytes; see the [running pace guide](/blogs/how-to-calculate-running-pace-5k-10k-half-marathon).`,
    ],
  },
};

export const EXTRA_POSTS: BlogPost[] = [
  {
    slug: 'how-many-calories-should-i-eat-per-day',
    title: 'How Many Calories Should I Eat Per Day? (Lose, Maintain or Gain)',
    category: 'Nutrition',
    excerpt: 'A step-by-step way to find your daily calories for fat loss, maintenance or muscle gain, with worked examples in kg and lbs.',
    image: '/images/calories.png',
    date: '2026-09-10',
    updated: '2026-09-28',
    readTime: '9 min read',
    region: 'Global',
    tools: ['calorie-calculator', 'tdee-calculator', 'macro-calculator'],
    faqs: [
      { q: 'How many calories should I eat to lose 1 kg a month?', a: 'One kilogram of fat is roughly 7,700 kcal, so a deficit of about 250 kcal per day loses around 1 kg a month. Most people aim for 300–600 kcal below maintenance.' },
      { q: 'What is the minimum number of calories I should eat?', a: 'As a general safety floor, avoid going below about 1,200 kcal (women) or 1,500 kcal (men) without medical supervision.' },
      { q: 'Do I need to eat back exercise calories?', a: 'Not usually. Your activity level is already built into your maintenance estimate, so eating extra on workout days can cancel your deficit.' },
    ],
    body: [
      `"How many calories should I eat?" has no single answer because it depends on your size, age, sex and activity. What it does have is a simple three-step method that works for almost everyone.`,
      `## Step 1: Find your maintenance calories`,
      `Maintenance is the amount that keeps your weight stable. It is your Basal Metabolic Rate (BMR) multiplied by an activity factor. The most accurate everyday formula is Mifflin-St Jeor:`,
      `- **Men:** BMR = 10 × weight (kg) + 6.25 × height (cm) − 5 × age + 5`,
      `- **Women:** BMR = 10 × weight (kg) + 6.25 × height (cm) − 5 × age − 161`,
      `Example: a 30-year-old woman, 65 kg and 165 cm, has a BMR of 650 + 1,031 − 150 − 161 = about 1,370 kcal. If she trains three times a week (factor 1.55) her maintenance is about 2,120 kcal. Skip the maths with the [calorie calculator](/tools/calorie-calculator) or the [TDEE calculator](/tools/tdee-calculator).`,
      `## Step 2: Pick an activity level honestly`,
      `- **1.2** – desk job, little exercise`,
      `- **1.375** – light exercise 1–3 days a week`,
      `- **1.55** – moderate exercise 3–5 days a week`,
      `- **1.725** – hard exercise 6–7 days a week`,
      `- **1.9** – physical job plus daily training`,
      `Most people are one level lower than they think. If unsure, choose the lower one and adjust.`,
      `## Step 3: Adjust for your goal`,
      `- **Lose fat:** eat 15–20% below maintenance (about 300–600 kcal). Expect 0.25–0.75 kg (0.5–1.5 lb) per week.`,
      `- **Maintain:** eat at maintenance.`,
      `- **Build muscle:** eat 5–10% above maintenance (about 150–300 kcal) and lift weights.`,
      `## Why calories are not the whole story`,
      `Two 1,800 kcal days can feel very different. Protein keeps you full and protects muscle, fibre keeps digestion regular, and whole foods are harder to overeat. After your calorie target, set protein at 1.6–2.2 g per kg with the [protein calculator](/tools/protein-calculator) and split the rest using the [macro calculator](/tools/macro-calculator).`,
      `## How to check and adjust`,
      `Follow your target for two to three weeks and track your average weekly weight rather than daily numbers. If weight is not moving in the direction you want, change intake by about 100–200 kcal and reassess. Recalculate every 4–6 weeks or after 2–3 kg of weight change, as described in our [TDEE guide](/blogs/tdee-calculator-guide-cutting-vs-bulking-2026).`,
      `## Special cases`,
      `Calorie needs are higher during pregnancy and breastfeeding, and lower with some medical conditions. Teenagers, people with a history of eating disorders, and anyone with diabetes or thyroid disease should get personalised advice from a doctor or registered dietitian rather than relying on a calculator alone.`,
      `## Bottom line`,
      `Estimate maintenance, adjust by 10–20% for your goal, track for a few weeks and tweak. The number you get is a starting point – your body's response is the real answer.`,
    ],
  },
  {
    slug: 'bmi-vs-body-fat-percentage-which-matters-more',
    title: 'BMI vs Body Fat Percentage: Which Number Matters More?',
    category: 'Health',
    excerpt: 'BMI is quick but flawed. Here is what it misses, when body fat percentage is a better guide, and how to use both.',
    image: '/images/bmi.png',
    date: '2026-09-12',
    updated: '2026-09-28',
    readTime: '8 min read',
    region: 'Global',
    tools: ['bmi-calculator', 'body-fat-calculator'],
    faqs: [
      { q: 'Is body fat percentage better than BMI?', a: 'For individuals, usually yes, because it separates fat from muscle. BMI is still useful as a fast, free screening tool for populations.' },
      { q: 'Can you have a normal BMI and still be unhealthy?', a: 'Yes. Some people have a normal BMI but high body fat and low muscle, sometimes called "normal weight obesity" or "skinny fat", with increased metabolic risk.' },
      { q: 'What waist size is a warning sign?', a: 'Risk rises above about 94 cm (37 in) for men and 80 cm (31.5 in) for women in European guidelines, and lower for South Asians (about 90 cm men, 80 cm women).' },
    ],
    body: [
      `BMI and body fat percentage both try to answer "is my weight healthy?" but they measure very different things. Understanding the difference stops you from over- or under-reacting to a single number.`,
      `## What BMI actually measures`,
      `BMI divides your weight by your height squared. It says nothing about what that weight is made of. It was designed in the 1830s for studying populations, not diagnosing individuals. Check yours with the [BMI calculator](/tools/bmi-calculator).`,
      `## Where BMI goes wrong`,
      `- **Muscular people** are often labelled overweight despite low body fat.`,
      `- **Low-muscle people** can have a "normal" BMI but too much fat.`,
      `- **South Asians** have higher risk at lower BMI, so cut-offs of 23 (overweight) and 27.5 (obese) are often used.`,
      `- **Older adults** lose muscle with age, so BMI can hide fat gain.`,
      `## What body fat percentage tells you`,
      `Body fat percentage is the share of your weight that is fat. It separates fat from lean tissue, which is what actually drives health risk and how you look. Rough fitness-to-average ranges are 14–24% for men and 21–31% for women. You can estimate yours with the tape-measure [body fat calculator](/tools/body-fat-calculator).`,
      `## The most useful add-on: waist measurement`,
      `Fat stored around the abdomen is the most harmful type. A waist above about half your height is a simple warning sign for any adult. It costs nothing and is far more informative than BMI alone.`,
      `## So which should you use?`,
      `Use BMI as a first screen, then confirm with body fat estimate and waist. If your BMI is high but you lift weights and your waist and body fat are healthy, BMI is misleading you. If your BMI is normal but your waist is large and you are inactive, do not be falsely reassured.`,
      `## How to improve either number`,
      `- Eat in a modest deficit if fat loss is the goal ([calorie calculator](/tools/calorie-calculator)).`,
      `- Lift weights twice or more per week to keep muscle.`,
      `- Eat enough protein (1.6–2.2 g/kg).`,
      `- Walk daily and sleep 7–9 hours.`,
      `## When to see a doctor`,
      `If you have a BMI over 30, a large waist, or conditions like high blood pressure, diabetes or PCOS, a doctor can order blood tests that reveal far more than any calculator. These tools are guides, not diagnoses.`,
    ],
  },
  {
    slug: 'how-to-calculate-running-pace-5k-10k-half-marathon',
    title: 'How to Calculate Running Pace for a 5K, 10K and Half Marathon',
    category: 'Workout',
    excerpt: 'Learn the pace formula, see target times for common distances, and get simple pacing rules that stop you fading in the final kilometres.',
    image: '/images/one-rep.png',
    date: '2026-09-15',
    updated: '2026-09-28',
    readTime: '8 min read',
    region: 'UK',
    tools: ['running-pace-calculator', 'calories-burned-calculator', 'water-intake-calculator'],
    faqs: [
      { q: 'What is a good running pace for beginners?', a: 'A comfortable beginner pace is often 6:30–8:00 per km (10:30–13:00 per mile). If you cannot chat while running, slow down.' },
      { q: 'How do I convert min/km to min/mile?', a: 'Multiply your pace per km by 1.609. For example, 6:00 per km is about 9:39 per mile.' },
      { q: 'How long does it take to run a 10K?', a: 'Beginners often take 60–75 minutes. Regular recreational runners take 45–60 minutes. It depends on training and terrain.' },
    ],
    body: [
      `Pace is the most useful number in running: how long it takes you to cover one kilometre or one mile. Once you can calculate it, you can plan races, set training paces and stop guessing.`,
      `## The pace formula`,
      `Pace = total time ÷ total distance. If you run 10 km in 55 minutes, your pace is 55 ÷ 10 = 5:30 per km. To convert to miles multiply by 1.609, giving about 8:51 per mile. The [running pace calculator](/tools/running-pace-calculator) does this instantly and predicts race times.`,
      `## Common race distances`,
      `- **5K:** 5 km (3.11 miles)`,
      `- **10K:** 10 km (6.21 miles)`,
      `- **Half marathon:** 21.0975 km (13.11 miles)`,
      `- **Marathon:** 42.195 km (26.22 miles)`,
      `## Example target times by pace (per km)`,
      `- **7:00/km:** 5K in 35:00, 10K in 1:10:00, half marathon in about 2:27`,
      `- **6:00/km:** 5K in 30:00, 10K in 1:00:00, half marathon in about 2:06`,
      `- **5:30/km:** 5K in 27:30, 10K in 55:00, half marathon in about 1:56`,
      `- **5:00/km:** 5K in 25:00, 10K in 50:00, half marathon in about 1:45`,
      `## Easy pace vs race pace`,
      `Most of your weekly running should be easy: a pace where you can hold a conversation, roughly 60–90 seconds per km slower than 5K race pace. Only one or two sessions a week should be faster. Running every run hard is the fastest route to injury and stagnation.`,
      `## Pacing a race`,
      `- **Start slightly slower** than target for the first kilometre. Adrenaline makes you feel faster than you are.`,
      `- **Aim for even splits** or a slightly faster second half.`,
      `- **In hot weather**, slow down 10–20 seconds per km and drink more; see the [water intake guide](/blogs/how-much-water-should-you-drink-daily).`,
      `## Predicting longer races from a shorter one`,
      `A common rule is that doubling the distance adds a little more than double the time, because fatigue accumulates. A 25:00 5K typically translates to roughly 52:00 for 10K and about 1:56–2:00 for a half marathon with proper training.`,
      `## Calories and recovery`,
      `A 70 kg runner burns roughly 600–700 kcal per hour at a moderate pace; check yours with the [calories burned calculator](/tools/calories-burned-calculator). Eat carbohydrate and protein after long runs, and increase weekly distance by no more than about 10% to reduce injury risk.`,
    ],
  },
  {
    slug: 'one-rep-max-formulas-explained-epley-brzycki',
    title: 'One Rep Max Formulas Explained: Epley vs Brzycki (With Examples)',
    category: 'Workout',
    excerpt: 'How to estimate your 1RM safely from a lighter set, what each formula assumes, and how to turn the result into training weights.',
    image: '/images/one-rep.png',
    date: '2026-09-18',
    updated: '2026-09-28',
    readTime: '7 min read',
    region: 'US',
    tools: ['one-rep-max-calculator'],
    faqs: [
      { q: 'Which 1RM formula is best?', a: 'Epley and Brzycki are both reasonable for sets of 10 reps or fewer. They usually agree within a few percent.' },
      { q: 'Can beginners use a 1RM calculator?', a: 'Yes, and it is safer than testing a true max. Use a set of 5–8 reps with good form.' },
      { q: 'What percentage of 1RM builds muscle?', a: 'Roughly 65–85% of 1RM for sets of about 6–12 reps is the common hypertrophy range.' },
    ],
    body: [
      `Your one-rep max (1RM) is the heaviest weight you can lift once with good form. Programmes often set training loads as a percentage of it, but a true max test is tiring and risky. Formulas let you estimate it from a lighter set.`,
      `## Epley formula`,
      `1RM = weight × (1 + reps ÷ 30). If you bench 80 kg for 8 reps: 80 × (1 + 8/30) = 80 × 1.267 = about 101 kg. Epley is the formula used in our [1RM calculator](/tools/one-rep-max-calculator).`,
      `## Brzycki formula`,
      `1RM = weight × 36 ÷ (37 − reps). The same set gives 80 × 36 ÷ 29 = about 99 kg. As you can see, the two agree within a couple of kilograms.`,
      `## Which is more accurate?`,
      `Both lose accuracy above about 10 reps because fatigue, not maximal strength, limits the set. For the best estimate use a hard set of 3–8 reps taken close to failure with a spotter or safety bars.`,
      `## Turning 1RM into training weights`,
      `- **90–100%:** singles and doubles for peak strength.`,
      `- **80–90%:** sets of 3–6 for strength.`,
      `- **65–80%:** sets of 6–12 for muscle growth.`,
      `- **50–65%:** technique, warm-ups and endurance.`,
      `For example, with a 100 kg squat 1RM, 75 kg for 8–10 reps is a good muscle-building load.`,
      `## Common mistakes`,
      `Do not use a warm-up set, a set with grinding form, or different exercise variations from week to week. Use the same lift, same range of motion and same equipment so your numbers are comparable.`,
      `## How often to update`,
      `Recalculate every 4–8 weeks. If you are new, strength rises quickly, so retest sooner. New to lifting? Start with our [strength training for beginners plan](/blogs/strength-training-for-beginners-uk-us-2026). Fuel your training with enough protein using the [protein calculator](/tools/protein-calculator).`,
    ],
  },
  {
    slug: 'high-protein-vegetarian-indian-foods',
    title: 'High-Protein Vegetarian Indian Foods: 15 Options With Protein Per Serving',
    category: 'Nutrition',
    excerpt: 'Hit your protein target on a vegetarian diet with everyday Indian foods, from dal and paneer to soya chunks, with a sample day of eating.',
    image: '/images/protein.png',
    date: '2026-09-22',
    updated: '2026-09-28',
    readTime: '8 min read',
    region: 'IN',
    tools: ['protein-calculator', 'macro-calculator'],
    faqs: [
      { q: 'Can I build muscle on a vegetarian Indian diet?', a: 'Yes. With enough total protein from dairy, paneer, dal, soya and eggs (if eaten), plus a calorie surplus and resistance training, muscle gain is fully possible.' },
      { q: 'Is dal a complete protein?', a: 'Dal is low in methionine, but combined with rice or roti across the day it provides all essential amino acids.' },
      { q: 'How much protein should a vegetarian eat?', a: 'Aim for about 1.6–2.2 g per kg of bodyweight if you train, and slightly above the 0.8 g/kg minimum otherwise.' },
    ],
    body: [
      `Getting enough protein is the number one challenge on a vegetarian diet in India, where many meals are carbohydrate heavy. The good news: everyday Indian foods can get you there without supplements.`,
      `## How much protein you need`,
      `Active people should aim for about 1.6–2.2 g per kg per day. A 70 kg person needs 110–150 g. Calculate your figure with the [protein calculator](/tools/protein-calculator).`,
      `## 15 high-protein vegetarian Indian foods (approximate values)`,
      `- **Soya chunks, 50 g dry:** 26 g – the highest protein per rupee.`,
      `- **Paneer, 100 g:** 18–20 g.`,
      `- **Greek yogurt or hung curd, 200 g:** 15–20 g.`,
      `- **Tofu, 150 g:** 12–15 g.`,
      `- **Moong dal, 1 cooked cup:** about 14 g.`,
      `- **Masoor and toor dal, 1 cooked cup:** 16–18 g.`,
      `- **Rajma and chole, 1 cooked cup:** 14–15 g.`,
      `- **Sprouted moong, 1 cup:** 7–9 g.`,
      `- **Peanuts, 30 g:** 7–8 g, or 2 tablespoons peanut butter for about 7 g.`,
      `- **Milk, 1 glass (250 ml):** 8 g.`,
      `- **Besan chilla, 2 medium:** about 12 g.`,
      `- **Quinoa, 1 cooked cup:** 8 g.`,
      `- **Almonds, 30 g:** 6 g.`,
      `- **Pumpkin seeds, 30 g:** 9 g.`,
      `- **Eggs, 2 large (if you eat them):** 12 g.`,
      `## Sample 100–110 g protein vegetarian day`,
      `- **Breakfast:** 2 besan chillas with curd – about 22 g.`,
      `- **Lunch:** 1 cup dal, rice, salad and 100 g paneer bhurji – about 38 g.`,
      `- **Snack:** roasted chana and a glass of milk – about 18 g.`,
      `- **Dinner:** soya chunk curry (40 g dry) with 2 rotis – about 30 g.`,
      `## Tips to raise protein without adding much fat`,
      `Swap plain rice for a dal-heavy plate, add a scoop of curd to every meal, and replace one snack with roasted chana or sprouts. Protein powder (whey or a plant blend) is a convenient extra, not a requirement.`,
      `## Combining foods`,
      `Most plant proteins are lower in one or two amino acids. Eating varied foods across the day – dal with rice, roti with paneer, legumes with grains – covers all essential amino acids. You do not need to combine them in every meal.`,
      `## Next steps`,
      `Set your total calories with the [calorie calculator](/tools/calorie-calculator), split macros with the [macro calculator](/tools/macro-calculator), and see our general guide to [high-protein foods](/blogs/high-protein-foods-for-muscle-building).`,
    ],
  },
];
